site_name: Create an SPA from 0 to 100 in nn steps
repo_url: https://github.com/MaquestiauxTraining/spa-0-100-eui
site_description: Welcome to Create an SPA from 0 to 100 in nn steps
site_author: Jean-Philippe Maquestiaux
nav:
  - Home: index.md
  - Purpose: purpose.md
  - Technologies: technologies.md
  - Building the application: building.md