site_name: Create an SPA
site_description: Welcome to Create an SPA from 0 to 100 in nn steps
site_author: Jean-Philippe Maquestiaux
nav:
  - Home: index.md
  - Purpose: purpose.md
  - Technologies: technologies.md
  - Building the application:
      - Start: building.md
      - Installing the necessary tools: necessary-tools.md
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 4