site_name: Create an SPA
site_description: Welcome to Create an SPA from 0 to 100 in nn steps
site_author: Jean-Philippe Maquestiaux
nav:
  - Home: 'Home.md'
  - Purpose: 'Purpose.md'
  - Technologies: 'Technologies.md'
  - Building the application:
      - Start: 'Building-the-application.md'
      - Installing the necessary tools: 'Necessary-Tools.md'
      - Initalise the application: 'Initialise-the-application.md'
  - Starting with the API: Starting-with-the-API.md''

theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 4