Starting with the API
=====================

Configure the database access
-----------------------------

Configure the /server/app/.env OR the /server/app/config/packages/doctrine.yaml

Configure the API Platform
--------------------------

Update the configuration files

- /server/app/config/packages/api_platform.yaml
- /server/app/config/routes/api_platform.yaml
